name: nortus
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.2.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.1
  go_router: ^17.0.0
  get_it: ^9.2.0
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.3.2
  flutter_result: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/logo/

icons_launcher:
  image_path: "lib/assets/logo/nortus_white_name.png"
  platforms:
    android:
      image_path: "lib/assets/logo/nortus_white_name.png"
      enable: true
      adaptive_background_color: "#0D478C"
      adaptive_foreground_image: "lib/assets/logo/nortus_white_name.png"
    ios:
      enable: true
      image_path: "lib/assets/logo/nortus_white_name.png"
